[workspace]
resolver = "2"
members = [
    "pallet-ismp/rpc",
    "pallet-ismp/runtime-api",
    "pallet-ismp/primitives",
    "pallet-ismp",
    "parachain/inherent",
    "parachain",
    "ismp-assets"
]
