[workspace]
resolver = "2"
members = [
    "pallet-ismp/rpc",
    "pallet-ismp/runtime-api",
    "pallet-ismp/primitives",
    "pallet-ismp/primitives/state-machine",
    "pallet-ismp/evm",
    "pallet-ismp",
    "parachain/inherent",
    "parachain/runtime-api",
    "parachain",
    "ismp-demo",
    "grandpa",
    "grandpa/primitives",
    "grandpa/verifier",
    "grandpa/prover"
]

[workspace.dependencies]
enum-as-inner = "=0.5.1"

#todo: remove on alloy v0.4.0 release
[patch.crates-io]
ruint = { git = "https://github.com/recmo/uint.git", rev = "e34200e114ac8fe93cf8e815e92601860ae4d7b8" }
