[workspace]
resolver = "2"
members = [
    "pallet-ismp/rpc",
    "pallet-ismp/runtime-api",
    "pallet-ismp/primitives",
    "pallet-ismp",
    "ismp-demo",
]

[workspace.dependencies]
enum-as-inner = "=0.5.1"

