[package]
name = "grandpa-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitives = { package = "grandpa-light-client-primitives", path = "./primitives", default-features = false }
