[package]
name = "ismp-primitives"
version = "0.1.0"
edition = "2021"
authors = ["Polytope Labs <hello@polytope.technology>"]

[dependencies]
# substrate
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.40", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.40", default-features = false }

# polytope labs
ismp = { git = "ssh://git@github.com/polytope-labs/ismp-rs.git", branch = "main", default-features = false }

# crates.io
merkle-mountain-range = { package = "ckb-merkle-mountain-range", version = "0.5.2", default-features = false }
codec = { package = "parity-scale-codec", version = "3.1.3", default-features = false }
primitive-types = { version = "0.12.1", default-features = false }

[features]
default = ["std"]
std = [
    "frame-system/std",
    "ismp/std",
    "merkle-mountain-range/std",
    "codec/std",
    "sp-runtime/std",
    "primitive-types/std",
]
