name: CI suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: recursive

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2023-09-13
          targets: wasm32-unknown-unknown

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.9.1'
          repo-token: ${{ secrets.GH_TOKEN }}

      - name: Build
        run: |
          cargo +nightly-2023-09-13 check --workspace --all-targets --all-features --verbose --locked

      - name: Build `no-std`
        run: |
          cargo +nightly-2023-09-13 check -p pallet-ismp --no-default-features --target=wasm32-unknown-unknown --verbose --locked
          cargo +nightly-2023-09-13 check -p ismp-demo --no-default-features --target=wasm32-unknown-unknown --verbose --locked

      - name: Test
        run: |
          cargo +nightly-2023-09-13 test -p pallet-ismp --all-targets --all-features --verbose --locked

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: recursive

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Check format
        run: cargo +nightly fmt --all --check
